openapi: 3.0.0
info:
    title: User Authentication API
    version: 1.0.0
    description: API documentation for user authentication

paths:
    /api/v1/user/login:
        post:
            summary: User Login
            description: Authenticate a user and obtain access and refresh tokens.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - email
                                - password
                            properties:
                                email:
                                    type: string
                                    format: email
                                    description: User's email address
                                password:
                                    type: string
                                    description: User's password
            responses:
                '201':
                    description: Successfully logged in
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthResponse'
                '401':
                    description: Invalid credentials
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

    /api/v1/user/logout:
        post:
            summary: User Logout
            description: Log out the user.
            responses:
                '201':
                    description: Successfully logged out
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SuccessResponse'

    /api/v1/user/refresh:
        post:
            summary: Refresh Access Token
            description: Refresh the access token using a valid refresh token.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            required:
                                - refreshToken
                            properties:
                                refreshToken:
                                    type: string
                                    description: Refresh token obtained during login
            responses:
                '201':
                    description: Access token refreshed successfully
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthResponse'
                '400':
                    description: Bad request or missing data
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'
                '401':
                    description: Invalid or expired refresh token
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Error'

components:
    schemas:
        AuthResponse:
            type: object
            properties:
                success:
                    type: boolean
                    description: Indicates if the operation was successful
                data:
                    type: object
                    properties:
                        user:
                            $ref: '#/components/schemas/User'
                        accessToken:
                            type: string
                            description: JWT access token
                        refreshToken:
                            type: string
                            description: JWT refresh token

        User:
            type: object
            properties:
                id:
                    type: string
                    description: User ID

        SuccessResponse:
            type: object
            properties:
                success:
                    type: boolean
                    description: Indicates if the operation was successful
                message:
                    type: string
                    description: Success message

        Error:
            type: object
            properties:
                success:
                    type: boolean
                    description: Indicates if the operation was successful
                error:
                    type: string
                    description: Error message
