## PROD
FROM node:18-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile && yarn cache clean
RUN yarn add -D typescript
COPY src/prisma ./prisma/
COPY . .
RUN npx prisma generate && yarn build
RUN yarn remove typescript

# Étape 2 : Production (image finale sans devDependencies)
FROM node:18-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/.env ./.env
COPY --from=builder /app/package.json /app/yarn.lock ./
EXPOSE 3001
CMD ["node", "dist/index.js"] 