FROM node:18-alpine AS build
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --production --frozen-lockfile \
    && yarn add -D typescript \
    && yarn cache clean
COPY src/prisma ./prisma/
COPY . .
RUN npx prisma generate \
    && yarn build \
    && npx prisma migrate deploy \
    && yarn remove typescript

FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
COPY --from=build /app/.env ./.env
COPY --from=build /app/package.json /app/yarn.lock ./
RUN npm install pm2 -g
EXPOSE 3001
CMD ["pm2-runtime", "dist/index.js"]